# Generated by Django 2.1.4 on 2019-01-05 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
            ],
            options={
                'verbose_name_plural': '权限组',
                'verbose_name': '权限组',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='action',
            field=models.CharField(default='', max_length=32, verbose_name='动作'),
        ),
        migrations.AddField(
            model_name='permission',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authority.PermissionGroup'),
        ),
    ]
